use crate::chain::chain_actor::ChainHandle;
use crate::network::node::NodeClient;
use crate::storage::content_id::ContentId;
use crate::storage::db::Storage;

/// B.U.D. Universal Gateway.
/// Resolves a BNS name (.bud) to content stored in B.U.D.
///
/// Bitswap + ContentDiscovery P2P fetch is integrated.
pub const MAX_GATEWAY_CONTENT_BYTES: usize = 10 * 1024 * 1024;

fn checked_gateway_content(source: &str, data: Vec<u8>) -> Result<Vec<u8>, String> {
    if data.len() > MAX_GATEWAY_CONTENT_BYTES {
        return Err(format!(
            "gateway content from {source} exceeds {MAX_GATEWAY_CONTENT_BYTES} bytes"
        ));
    }
    Ok(data)
}

fn verified_gateway_content(
    source: &str,
    cid: &ContentId,
    data: Vec<u8>,
) -> Result<Vec<u8>, String> {
    let data = checked_gateway_content(source, data)?;
    if ContentId::of(&data) != *cid {
        return Err(format!(
            "gateway content from {source} does not match ContentId {}",
            hex::encode(&cid.0[..8])
        ));
    }
    Ok(data)
}

/// Local sled lookup. `Ok(None)` means "not stored here" and leaves the caller
/// to the next source. `Err` means bytes were found but are not trusted.
fn read_local_storage(storage: &Storage, cid: &ContentId) -> Result<Option<Vec<u8>>, String> {
    match storage.get_content(cid) {
        Ok(chunk) => verified_gateway_content("local sled storage", cid, chunk).map(Some),
        Err(_) => Ok(None),
    }
}

/// Turn a recipe-based manifest into bytes, or `None` if it is not one.
///
/// `Ok(None)` means "this manifest is not a recipe" and leaves the caller to
/// the stored-byte paths. `Err` means the recipe exists but the generation is
/// untrustworthy; in that case the later paths are **not** fallen back to.
/// Falling through would serve bytes from another source under the same name
/// after an unverifiable generation.
fn render_from_recipe(
    manifest: &crate::storage::ContentManifest,
) -> Result<Option<Vec<u8>>, String> {
    use crate::storage::generated::ContentSource;
    let spec = match &manifest.source {
        ContentSource::Generated(spec) => spec,
        // Sealed recipes have no seed on chain: regenerating here would be
        // impossible, and falling through to stored bytes would serve the wrong
        // category under a Three name.
        ContentSource::SealedGenerated(_) => {
            return Err(
                "sealed recipe cannot be rendered without a view-granted seed; the chain holds no seed"
                    .into(),
            );
        }
        // `Hybrid` and `Derived` cannot be produced from the recipe alone: the
        // first carries a prefix that cannot be regenerated, and the second
        // depends on the master's bytes. Both are left to the stored-byte
        // paths.
        _ => return Ok(None),
    };
    let bytes = crate::storage::generated::generate_content(spec)
        .map_err(|e| format!("recipe did not produce its bytes: {e:?}"))?;
    // Verify that what was produced is what was requested. The recipe is on
    // chain, but the only thing saying the generator read it correctly is that
    // the identity holds.
    //
    // Two details determine the identity, and both are read from the
    // manifest.
    //
    // Source: the manifest identity **commits to** the source (see section 66),
    // `with_source` recomputes the identity. Comparing without the source
    // would compare against the identity of the same bytes without a source, and
    // even a correct generation would be refused.
    //
    // Slice length: identity is built over the shard list, so
    // the bytes must be sliced at the same size as the original. Assuming a single part
    // would refuse every multi-part object.
    let chunk_size = manifest
        .shards
        .first()
        .map_or(bytes.len(), |shard| shard.size as usize);
    let rebuilt = crate::storage::ContentManifest::from_bytes_sliced(
        &bytes,
        u32::try_from(chunk_size)
            .map_err(|_| "generated object is too large to slice".to_string())?,
    )
    .map_err(|e| format!("generated bytes could not be re-hashed: {e:?}"))?
    .with_source(manifest.source.clone());
    if rebuilt.manifest_id != manifest.manifest_id {
        return Err(
            "generated bytes do not hash to the manifest id that named them; \
             refusing to serve content the recipe does not produce"
                .into(),
        );
    }
    Ok(Some(bytes))
}

/// The maximum number of objects held in the generation cache.
///
/// A count, not bytes: each entry is already bounded by [`MAX_GATEWAY_CONTENT_BYTES`],
/// and the product of the two bounds gives worst-case memory. Bounding the count
/// is less code than counting bytes and gives the same guarantee.
pub const MAX_GENERATION_CACHE_ENTRIES: usize = 64;

/// A bounded cache so the recipe is not run over and over.
///
/// # What it changes and what it does not
///
/// For generatable content the bytes are **stored** nowhere; what is on chain is
/// the recipe, and validator disk load is zero in this class. This cache does not touch
/// that claim: it is an ephemeral, node-local, rebuildable
/// performance layer. Delete it and the system still works correctly, only
/// more slowly - and slowness is not the definition of storage.
///
/// # Why it is needed
///
/// Without a cache every request ran the recipe from scratch. For hot content that means
/// CPU proportional to the request count, and the cost is borne not by the requester
/// but by **whoever runs the gateway**. Because generation is deterministic the same recipe always
/// yields the same bytes; redoing the same computation buys nothing.
///
/// # Why it is bounded
///
/// An unbounded cache is an unbounded queue: an attacker requesting distinct names
/// drives the gateway out of memory. The eviction policy is **oldest entry**
/// (FIFO): a true LRU needs a write lock on the read path as well in order to
/// update access order; the aim here is not to keep hot content but to make
/// back-to-back requests for the same content cheap, and FIFO does that at the same
/// cost.
#[derive(Default)]
struct GenerationCache {
    /// The entries held in insertion order.
    entries: std::collections::VecDeque<(ContentId, Vec<u8>)>,
}

impl GenerationCache {
    fn get(&self, id: &ContentId) -> Option<Vec<u8>> {
        self.entries
            .iter()
            .find(|(key, _)| key == id)
            .map(|(_, bytes)| bytes.clone())
    }

    fn insert(&mut self, id: ContentId, bytes: Vec<u8>) {
        if self.entries.iter().any(|(key, _)| key == &id) {
            return;
        }
        while self.entries.len() >= MAX_GENERATION_CACHE_ENTRIES {
            self.entries.pop_front();
        }
        self.entries.push_back((id, bytes));
    }
}

pub struct BudGateway {
    chain: ChainHandle,
    network: Option<NodeClient>,
    storage: Option<Storage>,
    /// An ephemeral cache of generated content.
    ///
    /// `Mutex` because the gateway is read through a shared reference and
    /// writing to the cache happens on the read path. The lock is held only for lookup and insert;
    /// generation happens **outside** the lock, otherwise a slow
    /// recipe would stall the whole gateway.
    generation_cache: std::sync::Mutex<GenerationCache>,
}

impl BudGateway {
    pub fn new(chain: ChainHandle, network: Option<NodeClient>, storage: Option<Storage>) -> Self {
        Self {
            chain,
            network,
            storage,
            generation_cache: std::sync::Mutex::new(GenerationCache::default()),
        }
    }

    /// Primary entry point for D-Web resolution.
    /// Name: "ayaz.bud" → Returns raw bytes (HTML/Media).
    pub async fn fetch_name_content(&self, name: &str) -> Result<Vec<u8>, String> {
        // 1. Resolve Name → BnsResolved (storage_root + content_id)
        let resolved = self
            .chain
            .bns_resolve_full(name.to_string())
            .await
            .ok_or_else(|| format!("BNS name '{name}' not found"))?;

        if resolved.is_expired {
            return Err(format!("BNS name '{name}' expired"));
        }

        // 2. Derive ContentId from storage_root
        let storage_root = resolved
            .storage_root
            .ok_or_else(|| format!("BNS name '{name}' has no storage binding"))?;

        // storage_root is already a 32-byte content key; a ContentId tuple wrap is enough.
        let cid = ContentId(storage_root);

        // 3. Recipe-born content: the bytes are stored nowhere.
        //
        // This branch comes first because there is nothing for the others to look for.
        // The bytes of a `Generated` manifest exist neither on chain, nor in
        // local storage, nor on remote peers; what is on chain is the
        // **recipe**. Because all four fetch paths look for stored bytes,
        // every generated object used to come back from the gateway as "not
        // found": an object whose record was accepted, whose fee was computed
        // and whose replica target was set could not be read.
        //
        // `generate_content` turns the recipe into bytes and the result
        // is rehashed with `ContentManifest::from_bytes_sliced` and verified
        // against the manifest identity. So the gateway verifies what it produces:
        // if a wrong recipe produces wrong bytes the identity does not hold and
        // the request is refused.
        // Cache first: rerunning the same recipe for the same bytes buys
        // nothing. The lock is held only for the lookup.
        if let Ok(cache) = self.generation_cache.lock() {
            if let Some(bytes) = cache.get(&cid) {
                return checked_gateway_content("generation cache", bytes);
            }
        }

        if let Some(manifest) = self.chain.get_storage_manifest(cid).await {
            // Generation outside the lock: a slow recipe must not stall the whole gateway.
            if let Some(bytes) = render_from_recipe(&manifest)? {
                // Size is checked before the insert: an oversize object is
                // refused, and refusing it must not leave it in a cache whose
                // bound is stated as 64 entries of at most this size.
                let bytes = checked_gateway_content("on-demand generation", bytes)?;
                if let Ok(mut cache) = self.generation_cache.lock() {
                    cache.insert(cid, bytes.clone());
                }
                return Ok(bytes);
            }
        }

        // 4. Local storage lookup (cached content). NOT: Storage::get_content
        //    Currently a stub (scope: no blob store yet), so this branch
        //    naturally misses and the NotFound return falls through to a P2P error.
        if let Some(ref storage) = self.storage {
            if let Some(chunk) = read_local_storage(storage, &cid)? {
                return Ok(chunk);
            }
        }

        // 5. Node-local B.U.D. fetch through the running network stack.
        // This is not a full remote Bitswap requester yet, but it allows the
        // Gateway to read content from the node's own BudBitswap store when the
        // RPC server is co-located with storage.
        if let Some(ref network) = self.network {
            if let Ok(chunk) = network.fetch_local_content(cid.0).await {
                return verified_gateway_content("node-local B.U.D. store", &cid, chunk);
            }
        }

        // 6. Remote P2P Bitswap requester. If the content is not available locally,
        // We query connected remote peers over the network.
        if let Some(ref network) = self.network {
            if let Ok(chunk) = network.fetch_remote_content(cid.0).await {
                return verified_gateway_content("remote P2P peer", &cid, chunk);
            }
        }

        Err(format!(
            "Content {}:{} not available in local storage, local B.U.D. store, or remote P2P peers.",
            hex::encode(&storage_root[..8]),
            resolved
                .content_id.map_or_else(|| "none".to_string(), |c| hex::encode(&c.as_bytes()[..4]))
        ))
    }

    /// Produce the same recipe in the format the reader asks for.
    ///
    /// `fetch_name_content` returns the recipe's raw output: the generator
    /// produces whatever it produces. A browser wants SVG, a wallet a small PNG, a
    /// gallery another size. For a generated object all of these are born from the **same
    /// recipe**; none of them are stored.
    ///
    /// Format is part of the commitment. A recipe produced as PNG is **a
    /// different object** from the SVG of the same recipe, and `render_id`
    /// gives each its own
    /// identity. So the identity returned here is not the manifest identity but the
    /// format-dependent render identity; the caller cannot confuse the two because
    /// the function returns both together.
    ///
    /// Works only for recipe-born content. The format of stored bytes
    /// is already the bytes themselves; reformatting them is not a gateway's
    /// job.
    ///
    /// # Errors
    ///
    /// If the name does not resolve, the content is not recipe-bearing, or generation exceeds
    /// the format's bounds.
    pub async fn render_name_content(
        &self,
        name: &str,
        format: &crate::storage::render::RenderFormat,
    ) -> Result<(Vec<u8>, [u8; 32]), String> {
        let resolved = self
            .chain
            .bns_resolve_full(name.to_string())
            .await
            .ok_or_else(|| format!("BNS name '{name}' not found"))?;
        if resolved.is_expired {
            return Err(format!("BNS name '{name}' expired"));
        }
        let storage_root = resolved
            .storage_root
            .ok_or_else(|| format!("BNS name '{name}' has no storage binding"))?;
        let cid = ContentId(storage_root);
        let manifest = self
            .chain
            .get_storage_manifest(cid)
            .await
            .ok_or_else(|| format!("BNS name '{name}' resolves to no known manifest"))?;

        let spec = match &manifest.source {
            crate::storage::generated::ContentSource::Generated(spec) => spec,
            crate::storage::generated::ContentSource::SealedGenerated(_) => {
                return Err("sealed recipe cannot be rendered without a view-granted seed".into());
            }
            _ => {
                return Err("only recipe-born content can be rendered into a requested \
                            format; stored bytes already are their format"
                    .into());
            }
        };

        let bytes = crate::storage::render::render(spec, format)
            .map_err(|e| format!("render failed: {e:?}"))?;
        let bytes = checked_gateway_content("on-demand render", bytes)?;
        let id = crate::storage::render::render_id(format, &bytes);
        Ok((bytes, id))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::storage::generated::{ContentSource, GeneratedSpec, GeneratorId};
    use crate::storage::ContentManifest;

    fn corrupt_store(good: &[u8], bad: &[u8]) -> (tempfile::TempDir, Storage, ContentId) {
        let dir = tempfile::tempdir().expect("tempdir");
        let path = dir.path().to_str().expect("utf8 path").to_string();
        let cid = ContentId::of(good);
        {
            let raw = sled::open(&path).expect("raw sled");
            raw.insert(format!("CONTENT:{}", hex::encode(cid.0)).as_bytes(), bad)
                .expect("insert");
            raw.flush().expect("flush");
        }
        let storage = Storage::new(&path).expect("storage");
        (dir, storage, cid)
    }

    #[test]
    fn corrupted_local_bytes_are_refused() {
        let (_dir, storage, cid) = corrupt_store(b"honest bytes", b"tampered bytes");
        let err = read_local_storage(&storage, &cid).expect_err("tampered bytes must be refused");
        assert!(err.contains("ContentId"), "{err}");
    }

    #[test]
    fn honest_local_bytes_are_returned() {
        let (_dir, storage, cid) = corrupt_store(b"honest bytes", b"honest bytes");
        assert_eq!(
            read_local_storage(&storage, &cid).expect("honest read"),
            Some(b"honest bytes".to_vec())
        );
    }

    #[test]
    fn empty_content_is_verified_too() {
        let (_dir, storage, cid) = corrupt_store(b"", b"");
        assert_eq!(
            read_local_storage(&storage, &cid).expect("empty read"),
            Some(Vec::new())
        );
        let (_dir2, storage2, cid2) = corrupt_store(b"", b"x");
        assert!(read_local_storage(&storage2, &cid2).is_err());
    }

    #[test]
    fn missing_local_bytes_fall_through() {
        let (_dir, storage, _) = corrupt_store(b"a", b"a");
        let other = ContentId::of(b"never stored");
        assert_eq!(read_local_storage(&storage, &other).expect("miss"), None);
    }

    #[test]
    fn network_bytes_are_checked_against_the_id() {
        let cid = ContentId::of(b"real");
        assert!(verified_gateway_content("test", &cid, b"real".to_vec()).is_ok());
        assert!(verified_gateway_content("test", &cid, b"fake".to_vec()).is_err());
        assert!(verified_gateway_content("test", &cid, Vec::new()).is_err());
    }

    fn spec() -> GeneratedSpec {
        GeneratedSpec {
            generator: GeneratorId::Avatar,
            seed: [11u8; 32],
            output_len: 32 * 32,
            step_budget: 8_000,
        }
    }

    fn generated_manifest() -> ContentManifest {
        let spec = spec();
        let bytes = crate::storage::generated::generate_content(&spec).expect("generation");
        let len = u32::try_from(bytes.len()).expect("size");
        ContentManifest::from_bytes_sliced(&bytes, len)
            .expect("manifest")
            .with_source(ContentSource::Generated(spec))
    }

    /// Recipe-born content is readable through the gateway.
    ///
    /// The bytes are stored nowhere; all four fetch paths look for stored
    /// bytes. Without this branch every generated object returned "not found":
    /// an object whose record was accepted and whose replica target was set
    /// could not be read.
    #[test]
    fn a_recipe_is_rendered_on_demand() {
        let manifest = generated_manifest();
        let bytes = render_from_recipe(&manifest)
            .expect("the recipe has to be producible")
            .expect("generated content must return bytes");
        assert_eq!(bytes.len(), 32 * 32);
        // And what was produced is what was requested: the identity holds.
        //
        // The source is restored. The manifest identity commits to the source (section 66), so
        // the same bytes without a source give **a different identity**. Expecting that
        // fails even when generation works correctly - the first version of the test did
        // exactly that, and what it measured was its own setup, not generation.
        let len = u32::try_from(bytes.len()).expect("boyut");
        let rebuilt = ContentManifest::from_bytes_sliced(&bytes, len)
            .expect("manifest")
            .with_source(manifest.source.clone());
        assert_eq!(rebuilt.manifest_id, manifest.manifest_id);
    }

    /// If the produced bytes do not hold the manifest identity the request is refused.
    ///
    /// The recipe is on chain, but the only thing saying the generator read it correctly
    /// is that the identity holds. Without this check the gateway would serve
    /// bytes the recipe did not produce under the recipe's name.
    #[test]
    fn bytes_that_do_not_match_the_id_are_refused() {
        let mut manifest = generated_manifest();
        // The identity is changed, the recipe stays: generation no longer matches.
        manifest.manifest_id = crate::storage::ContentId([0xAAu8; 32]);
        let err = render_from_recipe(&manifest).expect_err("a mismatched identity must be refused");
        assert!(
            err.contains("do not hash to the manifest id"),
            "the reason must state the identity mismatch: {err}"
        );
    }

    /// Content not backed by a recipe does not enter this branch.
    ///
    /// `Ok(None)` means "this is not a recipe" and leaves the caller to the stored-byte
    /// paths; had it been `Err`, stored content could never be read.
    #[test]
    fn stored_content_falls_through_to_the_byte_paths() {
        let bytes = b"ordinary stored content".to_vec();
        let len = u32::try_from(bytes.len()).expect("boyut");
        let manifest = ContentManifest::from_bytes_sliced(&bytes, len).expect("manifest");
        assert!(
            render_from_recipe(&manifest)
                .expect("stored content is not an error")
                .is_none(),
            "stored content must not enter the generation branch"
        );
    }

    /// `Hybrid` and `Derived` are also left to the stored-byte paths.
    ///
    /// Neither can be produced from the recipe alone: the first carries a
    /// non-regenerable prefix, and the second depends on the master's bytes.
    /// Trying to produce them would mean presenting bytes that are not in hand
    /// as though they were.
    #[test]
    fn hybrid_content_is_not_rendered_from_the_recipe_alone() {
        let bytes = b"a prefix plus a recipe".to_vec();
        let len = u32::try_from(bytes.len()).expect("size");
        let manifest = ContentManifest::from_bytes_sliced(&bytes, len)
            .expect("manifest")
            .with_source(ContentSource::Hybrid {
                prefix_bytes: 4,
                spec: spec(),
            });
        assert!(
            render_from_recipe(&manifest)
                .expect("hybrid is not an error")
                .is_none(),
            "hybrid cannot be produced from the recipe alone"
        );
    }

    /// The generation cache does not exceed its bound and returns the right bytes.
    ///
    /// An unbounded cache is an unbounded queue: an attacker requesting distinct names
    /// drives the gateway out of memory. The bound's job is to prevent that
    /// without corrupting the correct answer.
    #[test]
    fn the_generation_cache_stays_within_its_bound() {
        let mut cache = GenerationCache::default();

        // Every entry up to the bound is kept.
        for i in 0..MAX_GENERATION_CACHE_ENTRIES {
            let id = ContentId([u8::try_from(i % 256).expect("mod 256"); 32]);
            cache.insert(id, vec![u8::try_from(i % 256).expect("mod 256")]);
        }
        assert_eq!(cache.entries.len(), MAX_GENERATION_CACHE_ENTRIES);

        // The first one in is still there - no eviction was needed yet.
        let first = ContentId([0u8; 32]);
        assert_eq!(cache.get(&first), Some(vec![0u8]));

        // An entry above the bound evicts the oldest; the size stays fixed.
        let fresh = ContentId([200u8; 32]);
        cache.insert(fresh, vec![9u8]);
        assert_eq!(
            cache.entries.len(),
            MAX_GENERATION_CACHE_ENTRIES,
            "the cache must not grow past the bound"
        );
        assert_eq!(
            cache.get(&fresh),
            Some(vec![9u8]),
            "the new entry must be kept"
        );
        assert_eq!(
            cache.get(&first),
            None,
            "the oldest entry must have been evicted"
        );

        // The same identity sits in the cache **once**. Without the duplicate check
        // the same object would eat another slot per request: the cache's
        // declared capacity is 64 objects, but the number of distinct objects it actually holds
        // could fall to one through repeats of a single hot item.
        // The bound would still hold - as a bound that does nothing.
        cache.insert(fresh, vec![9u8]);
        let copies = cache
            .entries
            .iter()
            .filter(|(key, _)| key == &fresh)
            .count();
        assert_eq!(copies, 1, "the same identity must sit in the cache once");
        assert_eq!(
            cache.get(&fresh),
            Some(vec![9u8]),
            "a duplicate entry must not be corrupted"
        );

        // No answer for an identity that is not cached - returning an old entry
        // under the wrong identity would make everything the gateway serves suspect.
        assert_eq!(cache.get(&ContentId([255u8; 32])), None);
    }
}
