//! Cryptographic domain-separation tag inventory.
//!
//! Every `BDLM_*` string literal that reaches a hash or signature in this
//! Workspace is listed here. The list exists so a reviewer can check the whole
//! Separation surface in one place, and so a tag can never be added, renamed or
//! Silently reused without appearing in this file.
//!
//! This is an inventory for collision review, not a proof of binding: being
//! Listed here says the tag is known, not that its usage is correct.
//!
//! The `domain_tag_inventory` tests enforce two properties: the inventory is
//! Free of duplicates and sorted, and it matches the tags actually present in
//! The source tree (checked by the Rust `domain-tags` gate in
//! `xtask/gates/src/gates/domain_tags.rs`; CI runs it with its canary).
//!
//! ## The legacy `BUDLUM_` prefix
//!
//! A generation of `BUDLUM_*` literals written before the rename still lives
//! in the tree. For a long time the gate scanned only the `BDLM_` prefix, so
//! that generation sat in the inventory's blind spot (measured: 23 separation
//! tags plus 14 non-domain strings). The decision (2026-08-22, by the user)
//! was to widen the scope rather than rename: the gate scans both prefixes and
//! the inventory lists all of them. The non-domain strings (environment
//! variable names, an HSM slot, a test name) stay on the list too. That keeps
//! the gate complete without an exemption list, and forces every new
//! `BUDLUM_*` literal through review in all cases.

/// Every domain-separation tag used across the workspace, sorted and unique.
///
/// The `BDLM_BUD_*` family and the other tags first written under `bud/`
/// joined the list on 2026-09-02, when the gate's scan was widened to that
/// tree: `bud/` had no tag gate of its own, and `BDLM_CONTENT_V1` is used on
/// both sides of the boundary.
pub const DOMAIN_TAGS: &[&str] = &[
    "BDLM_AI_AGENT_PAYMENTS",
    "BDLM_AI_AGENT_PAYMENT_PAYER_COMMITMENT_V1",
    "BDLM_AI_AGENT_PAYMENT_RECEIPT_V1",
    "BDLM_AI_AGENT_PAYMENT_REQUEST_COMMITMENT_V1",
    "BDLM_AI_AGENT_PAYMENT_SETTLEMENTS_V1",
    "BDLM_AI_AGENT_PAYMENT_SETTLEMENT_V1",
    "BDLM_AI_AGENT_PAYMENT_V1",
    "BDLM_AI_AGENT_REPUTATIONS",
    "BDLM_AI_AGENT_REPUTATION_V1",
    "BDLM_AI_CALLBACK_QUEUE",
    "BDLM_AI_CANCELLED",
    "BDLM_AI_EQUIVOCATIONS",
    "BDLM_AI_EXEC_PROOFS",
    "BDLM_AI_EXEC_PROOF_V1",
    "BDLM_AI_GUEST_PROGRAM_V1",
    "BDLM_AI_INPUT_V1",
    "BDLM_AI_MLP_WEIGHTS_V1",
    "BDLM_AI_MODELS",
    "BDLM_AI_MODEL_V1",
    "BDLM_AI_OUTCOMES",
    "BDLM_AI_OUTCOME_LEAF_V1",
    "BDLM_AI_OUTPUT_V1",
    "BDLM_AI_PERCEPTION_V1",
    "BDLM_AI_RECLAIMED",
    "BDLM_AI_REGISTRY_ROOT_V3",
    "BDLM_AI_REQUESTS",
    "BDLM_AI_REQUEST_ID_V3",
    "BDLM_AI_REQUEST_LEAF_V1",
    "BDLM_AI_RESULTS",
    "BDLM_AI_RESULT_LEAF_V1",
    "BDLM_AI_RESULT_SIG_V1",
    "BDLM_AI_SPEC_LEAF_V1",
    "BDLM_AI_VERIFIER_CEILINGS",
    "BDLM_AI_VERIFIER_QOS",
    "BDLM_AI_VERIFIER_QOS_V1",
    "BDLM_AI_VERIFIER_STAKES",
    "BDLM_AI_VERIFIER_WHITELIST",
    "BDLM_BFT_VOTE_V2",
    "BDLM_BLOCK_CONTEXT_ENTROPY_V1",
    "BDLM_BLOCK_V4",
    "BDLM_BLS_POP_V1",
    "BDLM_BNS_REGISTRY_V2",
    "BDLM_BRIDGE_ASSET_LEAF_V1",
    "BDLM_BRIDGE_EXPIRY_V1",
    "BDLM_BRIDGE_PAYLOAD_V1",
    "BDLM_BRIDGE_SETTLED_V1",
    "BDLM_BRIDGE_TRANSFER_V1",
    "BDLM_BUDZERO_ALARMLOG_V1",
    "BDLM_BUDZERO_QUARANTINE_V1",
    "BDLM_BUD_CHECKPOINT_V1",
    "BDLM_BUD_COLUMNAR_V1",
    "BDLM_BUD_CONTENT_V1",
    "BDLM_BUD_CROP_V1",
    "BDLM_BUD_CULLING_V1",
    "BDLM_BUD_DAS_EMPTY_V1",
    "BDLM_BUD_DAS_LEAF_V1",
    "BDLM_BUD_DAS_NODE_V1",
    "BDLM_BUD_DAS_OWNER_V1",
    "BDLM_BUD_DICT_V1",
    "BDLM_BUD_ENGINE_V1",
    "BDLM_BUD_ERASURE_V1",
    "BDLM_BUD_EXE_V1",
    "BDLM_BUD_JPEGRE_V1",
    "BDLM_BUD_LOGFIELD_V1",
    "BDLM_BUD_LRC_V1",
    "BDLM_BUD_MARKDOWN_V1",
    "BDLM_BUD_MERKLE_V1",
    "BDLM_BUD_MODEL_V1",
    "BDLM_BUD_MULTIFILE_V1",
    "BDLM_BUD_PACT_V1",
    "BDLM_BUD_PDF_V1",
    "BDLM_BUD_POR_V1",
    "BDLM_BUD_POW_V1",
    "BDLM_BUD_PRODUCTION_V1",
    "BDLM_BUD_RATIOCONS_V1",
    "BDLM_BUD_REGENBLOCK_V1",
    "BDLM_BUD_REGENERATION_V1",
    "BDLM_BUD_SEGMENT_ROOT_V1",
    "BDLM_BUD_SEGMENT_V1",
    "BDLM_BUD_SHAMIR_V1",
    "BDLM_BUD_SHARD_V1",
    "BDLM_BUD_SOCIAL_V1",
    "BDLM_BUD_TRIE_V1",
    "BDLM_BUD_TSSERIES_V1",
    "BDLM_BUD_V2",
    "BDLM_BUD_VIEW_V1",
    "BDLM_CAROUSEL_LOSS_TEST_V1",
    "BDLM_CAROUSEL_PRNG_V1",
    "BDLM_CONFIDENTIAL_BODY_V1",
    "BDLM_CONFIDENTIAL_COMMIT_V1",
    "BDLM_CONSENSUS_VALIDATOR_SET_V1",
    "BDLM_CONSTITUTION_REGISTRY_V1",
    "BDLM_CONTENT_SUBRANGE_DEAL_V1",
    "BDLM_CONTENT_SUBRANGE_OOR_V1",
    "BDLM_CONTENT_SUBRANGE_V1",
    "BDLM_CONTENT_V1",
    "BDLM_CONVERGENT_V1",
    "BDLM_CROSS_DOMAIN_MESSAGE_V2",
    "BDLM_DEED_MANIFEST_V1",
    "BDLM_DERIVED_CONTENT_V1",
    "BDLM_DEVELOPER_OS_MANIFEST_V1",
    "BDLM_DICTIONARY_REGISTRY_V1",
    "BDLM_DICT_COHORT_V1",
    "BDLM_DICT_COVER_V1",
    "BDLM_DOMAIN_COMMITMENT_V1",
    "BDLM_DOMAIN_CONFIG_V1",
    "BDLM_DOMAIN_EVENT_V1",
    "BDLM_DOMAIN_REGISTRY_LEAF_V1",
    "BDLM_DOMAIN_REGISTRY_LEAF_V2",
    "BDLM_DOMAIN_REGISTRY_LEAF_V3",
    "BDLM_DWEB_PASSPORT_PROOF_BUNDLE_V1",
    "BDLM_EMIT_FEED_V1",
    "BDLM_EMPTY_DOMAIN_EVENT_ROOT_V1",
    "BDLM_EMPTY_MERKLE_ROOT_V1",
    "BDLM_EVM_RECEIPT_LEAF_V1",
    "BDLM_EXTERNAL_INTAKE_V1",
    "BDLM_FINALITY_PROOF_V1",
    "BDLM_GENERATED_SPEC_V1",
    "BDLM_GENERATED_STREAM_V1",
    "BDLM_GLOBAL_BLOCK_V5",
    "BDLM_GOLDEN_V1",
    "BDLM_GOSSIP_MSG_V1",
    "BDLM_GOVERNANCE_STATE_V1",
    "BDLM_GRANT_ISSUE_V1",
    "BDLM_GRANT_REVOKE_V1",
    "BDLM_GUARDIAN_SELECT_V1",
    "BDLM_GUARDIAN_TOUR_V1",
    "BDLM_HUB_REGISTRY_V3",
    "BDLM_INVALID_VOTE_TRACKER_V2",
    "BDLM_L1_NOTE_REGISTRY_V1",
    "BDLM_LADDER_STEP_V2",
    "BDLM_LIVENESS_TRACKER_V3",
    "BDLM_LRC_LAYOUT_V1",
    "BDLM_MAINTENANCE_CODING_AUDIT_V1",
    "BDLM_MAINTENANCE_PLACEMENT_V1",
    "BDLM_MANIFEST_V1",
    "BDLM_MANIFEST_V4",
    "BDLM_MARKER_",
    "BDLM_MARKETPLACE_REGISTRY_V2",
    "BDLM_MERKLE_NODE_V1",
    "BDLM_MERKLE_ODD_PROMOTE_V1",
    "BDLM_MERKLE_ODD_SENTINEL_V1",
    "BDLM_MERKLE_TRIE_V1",
    "BDLM_MESSAGE_LEAF_V1",
    "BDLM_MOBILE_DEVICE_ID_V1",
    "BDLM_MOBILE_SELF_PROFILE_V1",
    "BDLM_NEG_LOCK",
    "BDLM_NFT_REGISTRY_V6",
    "BDLM_NONCE_LEAF_V1",
    "BDLM_NORMALIZED_ROOT_V1",
    "BDLM_NO_FINALITY_PROOF_YET_V1",
    "BDLM_NULLIFIER_DERIVE_V1",
    "BDLM_OPTX_SEG_V1",
    "BDLM_PACT_OUTPUT_V1",
    "BDLM_PACT_RESIDUAL_V1",
    "BDLM_PASSPORT_WARNING_V1",
    "BDLM_PERMISSIONLESS_REGISTRY_V1",
    "BDLM_POLLEN_ACCESS_GRANT_LEAF_V1",
    "BDLM_POLLEN_ACCESS_GRANT_SIGNING_V1",
    "BDLM_POLLEN_ACCESS_GRANT_V1",
    "BDLM_POLLEN_AI_INPUT_REF_V1",
    "BDLM_POLLEN_DATA_ASSET_LEAF_V1",
    "BDLM_POLLEN_DATA_ASSET_V1",
    "BDLM_POLLEN_ENCRYPTION_POLICY_V1",
    "BDLM_POLLEN_PROTECTED_CONTENT_V1",
    "BDLM_POLLEN_PURCHASE_RECEIPT_LEAF_V1",
    "BDLM_POLLEN_PURCHASE_RECEIPT_V1",
    "BDLM_POLLEN_PURCHASE_V1",
    "BDLM_POLLEN_SALE_AUTHORIZATION_LEAF_V1",
    "BDLM_POLLEN_SALE_AUTHORIZATION_SIGNING_V1",
    "BDLM_POLLEN_SALE_AUTHORIZATION_V1",
    "BDLM_POS_CACHE_POISON_V3",
    "BDLM_POS_EPOCH_RANDOMNESS_V3",
    "BDLM_POS_SLOT_SEED_COMPAT_V3",
    "BDLM_POS_SLOT_SEED_V3",
    "BDLM_POW_HEADER_V1",
    "BDLM_PQ_ANCHOR_AGG_V1",
    "BDLM_PQ_ANCHOR_ROTATION_REASON_V1",
    "BDLM_PQ_ANCHOR_ROTATION_V1",
    "BDLM_PQ_ANCHOR_V1",
    "BDLM_PQ_SIGN_V1",
    "BDLM_PROCESSED_HIGH_WATER_LEAF_V1",
    "BDLM_QR_FRAME_V2",
    "BDLM_QR_STREAM_ID_V1",
    "BDLM_RELAYER_POLICY_ENVELOPE_V1",
    "BDLM_RELAYER_POLICY_REGISTRY_V1",
    "BDLM_RELAYER_RESULT_V2",
    "BDLM_RELAYER_USER_INTENT_V1",
    "BDLM_RELAY_PROOF_HASH_V1",
    "BDLM_RELAY_RECORD_V1",
    "BDLM_RENDER_ID_V1",
    "BDLM_RETRIEVAL_CHALLENGE_RANGE_V1",
    "BDLM_RPC_CODING_AUDIT_ENTROPY_V1",
    "BDLM_RPC_STORAGE_CHALLENGE_ENTROPY_V1",
    "BDLM_SEALED_GENERATED_V1",
    "BDLM_SECUREDEDUP_V1",
    "BDLM_SETTLEMENT_PROOF_MARKET_STATE_V1",
    "BDLM_SETTLEMENT_PROOF_TASK_V2",
    "BDLM_SHARD_PLACEMENT_V1",
    "BDLM_SINGLE_SCREEN_V1",
    "BDLM_SOCIAL_DELETE_V1",
    "BDLM_SOVEREIGN_COMPLIANCE_EVIDENCE_V1",
    "BDLM_SOVEREIGN_DOMAIN_REGISTRY_V1",
    "BDLM_SOVEREIGN_DOMAIN_TEMPLATE_V1",
    "BDLM_STORAGE_AGG_V1",
    "BDLM_STORAGE_CHALLENGE_CONTEXT_V1",
    "BDLM_STORAGE_CODING_AUDIT_V1",
    "BDLM_STORAGE_DEAL_V1",
    "BDLM_STORAGE_OPEN_DEAL_TX_V1",
    "BDLM_STORAGE_PROVIDER_CHALLENGE_V1",
    "BDLM_STORAGE_PROVIDER_PROOF_V1",
    "BDLM_STORAGE_PROVIDER_PUT_V1",
    "BDLM_STORAGE_RANDOM_CHALLENGE_RANGE_V1",
    "BDLM_STORAGE_REGISTRY_V1",
    "BDLM_STORAGE_V1",
    "BDLM_STUB_RECEIPT_V1",
    "BDLM_TARIF_COMMIT_V1",
    "BDLM_TARIF_GENERATOR_V1",
    "BDLM_TARIF_GUESS_V1",
    "BDLM_TARIF_GUESS_V2",
    "BDLM_THREE_CAROUSEL_V1",
    "BDLM_THREE_NFT_META_V1",
    "BDLM_THREE_PAYLOAD_KEY_V1",
    "BDLM_THREE_PAYLOAD_V1",
    "BDLM_THREE_QR_FRAME_V1",
    "BDLM_THREE_QR_STREAM_FOLD_V1",
    "BDLM_THREE_QR_STREAM_ID_V1",
    "BDLM_THREE_QR_VIDEO_V1",
    "BDLM_THREE_RECIPE_SEALED_V1",
    "BDLM_THREE_RECIPE_V1",
    "BDLM_THREE_SEAL_NONCE2_V1",
    "BDLM_THREE_SEAL_NONCE_V1",
    "BDLM_THREE_VIDEO_RECIPE_V1",
    "BDLM_TX_V4",
    "BDLM_TX_V5",
    "BDLM_TX_V6",
    "BDLM_TX_V6_MULTISIG_ADDRESS",
    "BDLM_VALIDATOR_SET_COMMITMENT_V1",
    "BDLM_VAULT_V1",
    "BDLM_VERIFIER_REGISTRY_V1",
    "BDLM_VIEW_CLAIM_V1",
    "BDLM_VIEW_GRANT_REG_V1",
    "BDLM_VIEW_GRANT_V1",
    "BDLM_ZK_FIELDTRACE_V1",
    "BDLM_ZK_INIT",
    "BDLM_ZK_PROOF_PAYLOAD_V2",
];

/// Tags whose misuse would let an attacker move a signature or hash from one
/// Context into another that decides consensus, custody or settlement.
///
/// Kept separate from [`DOMAIN_TAGS`] so a careless edit that drops one of them
/// Fails a test that names the tag, instead of only shifting a count.
pub const CRITICAL_DOMAIN_TAGS: &[&str] = &[
    "BDLM_AI_AGENT_PAYMENT_SETTLEMENTS_V1",
    "BDLM_AI_AGENT_PAYMENT_SETTLEMENT_V1",
    "BDLM_BRIDGE_TRANSFER_V1",
    "BDLM_GOSSIP_MSG_V1",
    "BDLM_GRANT_ISSUE_V1",
    "BDLM_GRANT_REVOKE_V1",
    "BDLM_HUB_REGISTRY_V3",
    "BDLM_POS_CACHE_POISON_V3",
    "BDLM_TX_V4",
    "BDLM_TX_V5",
    "BDLM_TX_V6",
    "BDLM_TX_V6_MULTISIG_ADDRESS",
    "BDLM_VALIDATOR_SET_COMMITMENT_V1",
];

/// The `BUDLUM_`-prefixed separation tags left over from the generation before
/// the rename. Every one of them reaches a hash or a signature; moving them to
/// the `BDLM_` prefix is not a spelling preference but a wire/compatibility
/// decision, which is why they are kept apart. Sorted and unique; the
/// `domain-tags` gate goes red on anything outside the inventory and on
/// anything unused.
pub const BUDLUM_PREFIXED_DOMAIN_TAGS: &[&str] = &[
    "BUDLUM_ADDRESS_V2",
    "BUDLUM_BLS_SCALAR_SHA3_V0",
    "BUDLUM_BLS_SIG_DST_HI",
    "BUDLUM_BLS_SIG_DST_LO",
    "BUDLUM_GENESIS_TX",
    "BUDLUM_GUARDIAN_VOTE_V1",
    "BUDLUM_MLDSA87_SEED_V1",
    "BUDLUM_NOTE_BLINDING_V1",
    "BUDLUM_NOTE_SPEND_SECRET_V1",
    "BUDLUM_PACT_REGISTRY_V2",
    "BUDLUM_PKCS11_ED25519_BINDING_V1",
    "BUDLUM_POA_COMMIT_V1",
    "BUDLUM_POA_LEADER_V2",
    "BUDLUM_PQ_QC",
    "BUDLUM_PRECOMMIT",
    "BUDLUM_PREVOTE",
    "BUDLUM_PRIVATE_TRANSFER_AUTH_V1",
    "BUDLUM_PRIVATE_TRANSFER_COMMITMENT_V1",
    "BUDLUM_PRIVATE_TRANSFER_V1",
    "BUDLUM_STORAGE_PACT_V1",
    "BUDLUM_TEE_ATTESTATION_V1",
    "BUDLUM_VIEW_KEY_V1",
    "BUDLUM_VIEW_KEY_V1_ROT",
    "BUDLUM_VRF",
    "BUDLUM_WALLET_RECOVERY_PROPOSAL_V1",
];

/// Strings that pass the `BUDLUM_` prefix and character-set filter but are NOT
/// separation tags: environment variable names, an HSM slot label, the name of
/// a removed flag, a test constant. They do not count as separation surface,
/// yet they stay on the list. The reason is not contamination but the
/// simplicity of the gate: a gate with no exemption list forces every new
/// `BUDLUM_*` literal - tag or environment name alike - through this file, and
/// the distinction between the two classes lives here, in the document, not in
/// the code.
pub const BUDLUM_PREFIXED_NON_DOMAIN_LITERALS: &[&str] = &[
    "BUDLUM_CHAIN_ID",
    "BUDLUM_DB_PATH",
    "BUDLUM_MAINNET_VALIDATOR",
    "BUDLUM_METRICS_API_KEY",
    "BUDLUM_MOBILE_MODE",
    "BUDLUM_NETWORK",
    "BUDLUM_ROLE",
    "BUDLUM_RPC_ALLOWED_IPS",
    "BUDLUM_RPC_API_KEY_ENV",
    "BUDLUM_RPC_AUTH_REQUIRED",
    "BUDLUM_RPC_RATE_LIMIT_PER_MINUTE",
    "BUDLUM_TUR6_RPC_TEST_KEY",
    "BUDLUM_VALIDATOR_KEY",
];
